version: '3.8'

services:
  db:
    image: postgres:15.4
    restart: always
    ports:
      - "5445:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: ${DB_NAME}
    volumes:
      - ./postgres-db:/var/lib/postgresql/data
